---
services:
  db:
    image: muddanadevops/pyapp:db_image
    deploy:
      replicas: 1
    ports:
      - "3306:3306"
    networks:
      - mynetwork

  auth_service:
    image: muddanadevops/pyapp:auth_image
    deploy:
      replicas: 1
    ports:
      - "5001:5001"
    networks:
      - mynetwork
    depends_on:
      - db
    

  book_service:
    image: muddanadevops/pyapp:book_image
    deploy:
      replicas: 1
    ports:
      - "5002:5002"
    networks:
      - mynetwork
    depends_on:
      - db
  borrow_service:
    image: muddanadevops/pyapp:borrow_image
    deploy:
      replicas: 1
    ports:
      - "5003:5003"
    networks:
      - mynetwork
    depends_on:
      - db

  frontend:
    image: muddanadevops/pyapp:frontend
    deploy:
      replicas: 1
    ports:
      - "5000:5000"
    networks:
      - mynetwork
    depends_on:
      - auth_service
      - book_service
      - borrow_service

networks:
  mynetwork:
    driver: bridge
